sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
  - '0.10'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run travis-after-all
branches:
  only:
    - master
