sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run travis-after-all
branches:
  only:
    - master
