sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 'node'
  - '7'
  - '6'
  - '4'
before_script:
  - 'if [ -n "${TEST_ESLINT_3-}" ]; then npm install eslint@^3.12.0; fi'
  - npm prune
script:
  - 'if [ -n "${LINTONLY-}" ]; then npm run lint; else npm run cover && npm run check-coverage; fi'
after_success:
  - npm run travis-after-all
matrix:
  include:
    - node_js: "node"
      env: TEST_ESLINT_3=true
    - node_js: "7"
      env: TEST_ESLINT_3=true
    - node_js: "6"
      env: TEST_ESLINT_3=true
    - node_js: "4"
      env: TEST_ESLINT_3=true
    - node_js: "node"
      env: LINTONLY=true
branches:
  only:
    - master
