sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
  - '0.10'
before_install:
  # detect if the current build's node version is < 4
  # if yes, install latest npm version 2.x
  # if not, install latest npm version 3.x
  - if [[ `node -v | sed 's/[^0-9\.]//g'` < 4 ]]; then npm i -g npm@^2.0.0; else npm i -g npm@^3.0.0; fi
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run travis-after-all
branches:
  only:
    - master
